# Generated by Django 2.2.19 on 2021-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
    ]
