# Generated by Django 2.2.19 on 2021-03-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('By', models.CharField(max_length=1000)),
                ('Title', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
                ('MinsToRead', models.IntegerField()),
            ],
        ),
    ]
