# Generated by Django 2.2.19 on 2021-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('TypeContent', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Publish Blogs',
            },
        ),
    ]
