# Generated by Django 2.2.19 on 2021-03-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='MinsToRead',
            new_name='TimeToRead',
        ),
    ]
