# Generated by Django 2.2.19 on 2021-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0002_auto_20210312_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='topic',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
    ]
