# Generated by Django 2.2.19 on 2021-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0003_trending_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='Image',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
