# Generated by Django 2.2.19 on 2021-03-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0004_trending_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trending',
        ),
    ]
