# Generated by Django 2.2.19 on 2021-03-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0006_publishblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishblog',
            options={'verbose_name_plural': 'Publish Blogs'},
        ),
    ]
