# Generated by Django 2.2.19 on 2021-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('Category', models.CharField(choices=[('Laptop', 'Laptop')], max_length=356)),
                ('StockDetails', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=356)),
            ],
            options={
                'verbose_name_plural': 'All Products',
            },
        ),
    ]
