# Generated by Django 2.2.19 on 2021-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showproducts',
            name='CurrentPrice',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showproducts',
            name='OFF',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showproducts',
            name='PastPrice',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5),
            preserve_default=False,
        ),
    ]
