# Generated by Django 2.2.19 on 2021-03-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210317_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showproducts',
            options={'verbose_name_plural': 'AllProducts'},
        ),
    ]
