# Generated by Django 2.2.19 on 2021-03-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210323_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showproducts',
            options={'verbose_name_plural': 'All Products'},
        ),
    ]
