# Generated by Django 2.2.19 on 2021-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210323_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='showproducts',
            name='Gender',
            field=models.CharField(choices=[('1', 'Men'), ('2', 'Women')], default=True, max_length=20),
            preserve_default=False,
        ),
    ]
