# Generated by Django 2.2.19 on 2021-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_showproducts_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproducts',
            name='Gender',
            field=models.CharField(choices=[('1', 'Men'), ('2', 'Women')], default='1', max_length=20),
        ),
    ]
